version: '3.1'

services:

  mysql:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: unifesspa
    ports:
      - "3306:3306"